### ISSUE TITLE
Missing File with latest install (Microsoft.AzureIntegrationMigration.Runner, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null)

### ISSUE THREAD

**Issue by billchesnut** [Azure/aimtool#8]
## Description

[11:51:02 INF] Finding stage runners.
[11:51:02 INF] Searching for IStageRunner in C:\ProgramData\chocolatey\lib\biztalkmigrator\tools\bin.
[11:51:02 INF] Found 1 libraries in C:\ProgramData\chocolatey\lib\biztalkmigrator\tools\bin.
[11:51:02 INF] Scanning...
[11:51:03 DBG] Ignoring library C:\ProgramData\chocolatey\lib\biztalkmigrator\tools\bin\Microsoft.AzureIntegrationMigration.BizTalk.StageRunners.dll due to missing dependencies.
[11:51:03 DBG] System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AzureIntegrationMigration.Runner, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Microsoft.AzureIntegrationMigration.Runner, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null'
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AzureIntegrationMigration.Runner, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Microsoft.AzureIntegrationMigration.Runner, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at Microsoft.AzureIntegrationMigration.Tool.Plugins.PluginAssemblyLoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)

   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Microsoft.AzureIntegrationMigration.Tool.Plugins.PluginFinder`1.FindPluginAssemblies(String pluginPath, Type[] sharedTypes)

[11:51:03 DBG] No stage runner assemblies found in C:\ProgramData\chocolatey\lib\biztalkmigrator\tools\bin.
[11:51:03 WRN] No stage runner assemblies found.
[11:51:03 INF] Finding model provider.
[11:51:03 INF] Searching for IApplicationModelProvider in C:\ProgramData\chocolatey\lib\biztalkmigrator\tools\bin.
[11:51:03 INF] Found 1 libraries in C:\ProgramData\chocolatey\lib\biztalkmigrator\tools\bin.
[11:51:03 INF] Scanning...
[11:51:04 DBG] Ignoring library C:\ProgramData\chocolatey\lib\biztalkmigrator\tools\bin\Microsoft.AzureIntegrationMigration.BizTalk.StageRunners.dll due to missing dependencies.
[11:51:04 DBG] System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AzureIntegrationMigration.Runner, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Microsoft.AzureIntegrationMigration.Runner, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null'
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AzureIntegrationMigration.Runner, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Microsoft.AzureIntegrationMigration.Runner, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at Microsoft.AzureIntegrationMigration.Tool.Plugins.PluginAssemblyLoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)

   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Microsoft.AzureIntegrationMigration.Tool.Plugins.PluginFinder`1.FindPluginAssemblies(String pluginPath, Type[] sharedTypes)

[11:51:04 DBG] No model provider assembly found in C:\ProgramData\chocolatey\lib\biztalkmigrator\tools\bin.
[11:51:04 WRN] No model provider assembly found.
[11:51:04 ERR] Failed to build runner: Failed to find a model provider.
[11:51:04 ERR] Full exception details:
System.ApplicationException: Failed to find a model provider.
   at Microsoft.AzureIntegrationMigration.Tool.App.<BuildRunner>b__15_0()
   at Microsoft.AzureIntegrationMigration.Runner.Builder.RunnerBuilder.Build()
   at Microsoft.AzureIntegrationMigration.Tool.App.BuildRunner()
   at Microsoft.AzureIntegrationMigration.Tool.App.RunAsync(CancellationToken token)
[11:51:04 DBG] Hosting stopping
[11:51:04 INF] Application is shutting down...
[11:51:04 DBG] Hosting stopped

## Environment and tool versions

Clean install with choco install biztalkmigrator --pre

**Comment by 345paul** [comment]
Thanks @billchesnut, I’ll take a look at this. We are currently trying to get a stable release through the Chocolatey moderation process and have been releasing new versions as part of that process and these changes may have caused this issue.

**Comment by 345paul** [comment]
Hi @billchesnut, I've tried to repro this issue and I am unable to.  Please could you try uninstalling and re-installing the tool?

To uninstall (and uninstall the dependencies) use:

`choco uninstall -fx biztalkmigrator`

Please also check in the `C:\ProgramData\chocolatey\lib` directory that the following directories have been deleted after the uninstall:

```
biztalkmigrator
biztalkmigrator-azure
biztalkmigrator-cli
```

And then to reinstall:

`choco install biztalkmigrator --pre`

We'll be able to drop the `--pre` hopefully soon once the Chocolatey packages have completed going through the manual moderation process.

**Comment by billchesnut** [comment]
Thanks, Paul, that worked, the key was the -fx I had tried to uninstall and reinstall

**Comment by billchesnut** [comment]
closed

**Comment by billchesnut** [comment]
close

**Comment by 345paul** [comment]
Thanks Bill, appreciate you updating the issue with the outcome.
